title       = "genk"
baseURL     = "https://genk-cli.tamnd.com/"
description = "A command line for genk."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/genk-cli"
